### ISSUE TITLE
[subset] AssertionError raised when HVAR.AdvWidthMap is None

### ISSUE THREAD

**Issue by signalwerk** [fonttools/fonttools#1237]
I try to get fonttools running. First I tried on my macOS. No luck. Then I tried to spin up a docker to make sure it's not my computer. My Dockerfile runs like that:

```
FROM ubuntu:trusty
ENV LANG C.UTF-8

# Prerequisites
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y python python-pip python-dev


# additional packages for fonttools
RUN pip install zopfli && pip install brotli

# ---------------------------------------------------
# pip doesn't work
# ---------------------------------------------------
# RUN pip install fonttools

# ---------------------------------------------------
# manually works
# ---------------------------------------------------
RUN apt-get install -y git
RUN \
  pip install virtualenv && \
  git clone https://github.com/fonttools/fonttools.git && \
  cd fonttools && \
  python -m virtualenv fonttools-venv && \
  . fonttools-venv/bin/activate && \
  ls -la && \
  pip install -e .

```

when I try `pyftsubset bigfont.ttf --text="E" --output-file=SubsettedFont.ttf` I get several errors. 

Any idea? Someone having a running docker for me?

```
Traceback (most recent call last):
  File "/fonttools/fonttools-venv/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'pyftsubset')()
  File "/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/fonttools/Lib/fontTools/subset/__init__.py", line 3281, in main
    subsetter.subset(font)
  File "/fonttools/Lib/fontTools/subset/__init__.py", line 3094, in subset
    self._subset_glyphs(font)
  File "/fonttools/Lib/fontTools/subset/__init__.py", line 3041, in _subset_glyphs
    retain = table.subset_glyphs(self)
  File "/fonttools/Lib/fontTools/subset/__init__.py", line 1769, in subset_glyphs
    assert table.AdvWidthMap, "File a bug."
AssertionError: File a bug.
```

**Comment by anthrotype** [comment]
hello, thanks for the report. That error has nothing to do with "CLI interface" (as the issue title suggests) or your docker setup (which looks correct).
The assertion error is raised because the font you are trying to subset has an HVAR table that has a null advance width mapping table, and the subsetter doesn't handle that case yet.
@behdad added a TODO in the line above, to "Handle direct mapping".

**Comment by anthrotype** [comment]
looks like @behdad did implement the HVAR direct mapping subsetting, but forgot to remove the assert 
https://github.com/fonttools/fonttools/commit/f01c86ca9be788ac16c86a60dc70241aa98287ea

I'll try to remove it and see if that fixes your issue.

@signalwerk could you send me a copy of the font that triggers this error (privately)? Thanks

**Comment by behdad** [comment]
> now I get WARNING: cvar NOT subset; don't know how to subset; dropped.

Fixed that one now too.

**Comment by anthrotype** [comment]
thanks behdad!

**Comment by signalwerk** [comment]
@anthrotype @behdad it's running through now! perfect. ((my font is still broken, but that has nothing to do with fonttools. Thank you guys!
