### ISSUE TITLE
[varLib.featureVars] Buggy

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1400]
From Just:
```
from pprint import pprint
from fontTools.varLib.featureVars import overlayFeatureVariations

rules = [
    ([{'abcd': (4, 9)}], {0: 0}),
    ([{'abcd': (5, 10)}], {1: 1}),
    ([{'abcd': (0, 8)}], {2: 2}),
    ([{'abcd': (3, 7)}], {3: 3}),
]

pprint(overlayFeatureVariations(rules))

-->

[({'abcd': (5, 7)}, [{0: 0}, {1: 1}, {2: 2}, {3: 3}]),
 ({'abcd': (7, 8)}, [{0: 0}, {1: 1}, {2: 2}]),
 ({'abcd': (4, 5)}, [{0: 0}, {2: 2}, {3: 3}]),
 ({'abcd': (3, 7)}, [{2: 2}, {3: 3}]),
 ({'abcd': (8, 9)}, [{0: 0}, {1: 1}]),
 ({'abcd': (8, 10)}, [{1: 1}])]

There is no rule vor (0, 3) in the overlayed ruleset.

Here’s another one:

rules = [
    ([{'abcd': (1, 9)}], {0: 0}),
    ([{'abcd': (8, 10)}], {1: 1}),
    ([{'abcd': (3, 4)}], {2: 2}),
    ([{'abcd': (1, 10)}], {3: 3}),
]

pprint(overlayFeatureVariations(rules))

-->

[({'abcd': (3, 4)}, [{0: 0}, {2: 2}, {3: 3}]),
 ({'abcd': (8, 9)}, [{0: 0}, {1: 1}, {3: 3}]),
 ({'abcd': (8, 10)}, [{1: 1}, {3: 3}]),
 ({'abcd': (4, 8)}, [{0: 0}, {3: 3}]),
 ({'abcd': (1, 10)}, [{3: 3}])]

For an axis value of 2, both {0: 0} and {3: 3} should trigger, but only {3: 3} ends up in the overlayed list.
```

**Comment by behdad** [comment]
Fixed.  Would be nice if someone can add these to to the test suite.

**Comment by justvanrossum** [comment]
I'll add this to featureVars_test.py, thanks.

**Comment by justvanrossum** [comment]
Unfortunately this doesn't fix Akiem's problem. Will try to reduce that one to a test.

**Comment by underware** [comment]
Yes, all works as expected. Thanks for the quick fix!
However, my manually written GSUB is still around 15% smaller...

**Comment by behdad** [comment]
>  However, my manually written GSUB is still around 15% smaller...

I can try optimizing if you can share.  I know the current algorithm doesn't produce optimal output, but I couldn't produce test cases exhibiting that.  Or most probably, it's about how we combine lookups or don't.  Anyway, hard to tell or do anything without seeing what you did and what the code does.

**Comment by justvanrossum** [comment]
Here's a script that builds a test font based on Underware's data, anonymized. Not sure if 15% is worth the effort, though...

[buildfeavartestfont.py.zip](https://github.com/fonttools/fonttools/files/2651983/buildfeavartestfont.py.zip)

**Comment by behdad** [comment]
Thanks.  15% is not the point.  I like to see what better packing approach Akiem is using and try to achieve it.

**Comment by underware** [comment]
What I am doing is rather primitive. Instead of using lookups, I define the substitutions directly inside the feature variations.

**Comment by justvanrossum** [comment]
If you can share, a `ttx -t GSUB font.ttf`dump would be helpful.

**Comment by behdad** [comment]
> What I am doing is rather primitive. Instead of using lookups, I define the substitutions directly inside the feature variations.

I'm guessing that that just doesn't do anything.  Does it work?!

**Comment by behdad** [comment]
I see the difference.  What you are doing is to create one lookup per changeset.  Whereas in the code, Just originally decided, to generate one lookup per input changeset and reference multiple lookups from each region.  This is typically beneficial by not duplicating the lookup content multiple times.  But in your case, combining is more compact.  Let me think, we can probably find out what the optimal combination is and produce that...
