### ISSUE TITLE
[subset] CFF assert len(bytes) == nBytes with glyphs using different hint mask bytes & sharing subrs

### ISSUE THREAD

**Issue by blueshade7** [fonttools/fonttools#1493]
`pyftsubset` fails to subset the attached mod-copy of SourceSerifPro with `--desubroutinize` option, when two glyphs `y` and `yacute` use different number of hint mask bytes (1 & 2) while sharing some subroutines.

```
% pyftsubset y_yacute.otf --unicodes=79,fd --output-file=output.otf --desubroutinize
Traceback (most recent call last):
  File "/usr/local/bin/pyftsubset", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/__init__.py", line 2827, in main
    subsetter.subset(font)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/__init__.py", line 2631, in subset
    self._prune_post_subset(font)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/__init__.py", line 2614, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/cff.py", line 427, in prune_post_subset
    self.desubroutinize()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/cff.py", line 454, in desubroutinize
    decompiler.execute(c)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/cff.py", line 374, in execute
    psCharStrings.SimpleT2Decompiler.execute(self, charString)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/misc/psCharStrings.py", line 300, in execute
    rv = handler(index)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/misc/psCharStrings.py", line 358, in op_hintmask
    hintMaskBytes, index = self.callingStack[-1].getBytes(index, self.hintMaskBytes)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/misc/psCharStrings.py", line 1062, in getBytes
    assert len(bytes) == nBytes
AssertionError
```

**Comment by blueshade7** [comment]
[y_yacute.otf.zip](https://github.com/fonttools/fonttools/files/2843241/y_yacute.otf.zip)

**Comment by anthrotype** [comment]
Is that from fonttools/master or the current stable release? I pushed a fix for desubroutinize yesterday, maybe that fixed (or broke) it?

**Comment by blueshade7** [comment]
Doesn't seem matter. Seems to repro with the master or 3.37.3 or 3.35.0.

**Comment by readroberts** [comment]
I can look at this. I can already guess what the problem is, after looking at the charstrings, and suspect it is a very old bug.

**Comment by behdad** [comment]
Interesting.  In general we consider it an error if a subroutine can be decompiled multiple ways.  Ie. if referenced with different hintmask bytes AND has hintmask.  I don't think we enforce this anywhere though.

**Comment by blueshade7** [comment]
No subr is interpreted in two ways; AFDKO wouldn’t generate such a font. All hintmask operators appear in charstrings, not in shared subroutines. The offending subr seems:
```
[-103]={
  hstemhm
  return
}
```
called by two glyphs with different sets of operands on stack generating different numbers of stem hints. The attached font is a manually crafted POC, but based on an actual failure observed with a shipping font which I can’t post here for a license reason.

tx and hb-subset have no problem in processing this font.

**Comment by readroberts** [comment]
This bug is not all what I had guessed. This is a bug in  fontTools/subset/cff.py:: _DesubroutinizingT2Decompiler.execute(). The problem is that the execute() function returns immediately if the subr has already been seen.  This is bad because 'execute()' needs to be applied to the subr if it contains hint values that will contribute to a later hint mask byte length calculation.  The easiest fix, and a simple patch for the moment,  is to simply always call psCharStrings.SimpleT2Decompiler.execute() in this function before returning, but this is too much overhead for a real fix. I think it will be easy to return immediately unless  (the charstring is a subr) and  (we don't know yet if we are doing hintmasks). I will try to think if there is a way to avoid even this much work.

Incidentally, this is a bad font. In both glyphs y and yacute, the charstring has  v hint values and the vstemhm operator *following* the first hintmask operator. This is illegal. It works in these glyphs because  in both cases there aren't enough v hints following the hintmask to require an addition mask byte, so the hint mask byte length matches the length needed for just the h hints that have been seem to date.

**Comment by blueshade7** [comment]
[y_yacute2.otf.zip](https://github.com/fonttools/fonttools/files/2847631/y_yacute2.otf.zip)
Fixed illegal placement of hintmask operators in font `y_yacute.otf` as `y_yacute2.otf`.
The only hintmask operator in glyph "y" is placed just before `endchar` making no sense, but still reproduces the failure in `pyftsubset`.

**Comment by readroberts** [comment]
@blueshade7 Yes, I would expect that.  The bug in pyftsubset has nothing to do with the separate bug in the original font. Can I check in  y_yacute2.otf as part of the  test case for the pyftsubset bug?

**Comment by cjchapman** [comment]
Fixed by https://github.com/fonttools/fonttools/pull/1499

**Comment by blueshade7** [comment]
[y_acute3.otf.zip](https://github.com/fonttools/fonttools/files/2890536/y_acute3.otf.zip)
The attached font still fails with this command line:
```
pyftsubset  y_acute3.otf --desubroutinize --output-file=output.otf --unicodes=79,fd
```
**Notes:**
The two glyphs share both local subrs and global subrs. This may be a factor?
The actual font & glyphs causing this failure are `s.sc` and `scaron.sc` in TektonPro-LightCond.otf.
Modified & simplified & transplanted the charstrings as `y` and `yacute` in SourceSerifPro.otf shell.
