### ISSUE TITLE
different ClassDef values between python 2 and 3

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#766]
It turns out that fonts built with python 2 and 3 may end up having different GPOS tables, because of the non-deterministic way `ClassDef` class definition tables are encoded in feaLib/otlLib.

The following patch:
https://github.com/fonttools/fonttools/compare/issue-766?expand=1

.. produces different test outputs, in a seemingly random fashion:
https://travis-ci.org/fonttools/fonttools/jobs/183647027

I think the problem lies in this line, where a list of sets of (glyph names) strings is sorted by the length of the sets:
https://github.com/fonttools/fonttools/blob/f81e1411b3fb1ca402065fbd9a3c53907d205b58/Lib/fontTools/otlLib/builder.py#L622

If two sets have the same length the order of the set list is not guaranteed to be the same all the time, as they might be hashed differently by different implementations, sometimes even by the same one at different times.

We need to find a better way to sort the ClassDef.

/cc @brawer

**Comment by behdad** [comment]
Fixed, but didn't test.

**Comment by anthrotype** [comment]
I spoke too fast in https://github.com/fonttools/fonttools/commit/7d1ddb237ec2f4c6d4982ff076fd15c1d47771f2#commitcomment-20329688

The test for ClassDef sets with same length is still failing in a random fashion:
https://travis-ci.org/fonttools/fonttools/jobs/187721425
https://ci.appveyor.com/project/fonttools/fonttools/build/1.0.329/job/u2vg1dn24w2jwvt7

Shall I mark it as `xfail` until we find a better fix?

**Comment by anthrotype** [comment]
I tried to restart the Travis build (which was apparently passing), and now is failing again, and on the same commit:

https://travis-ci.org/fonttools/fonttools/builds/187819971

So we need to find another sorting method for ClassDef sets.

**Comment by justvanrossum** [comment]
I don't completely follow everything here, but it seems that in the ClassDefBuilder canAdd() and add() methods the glyphs collection is converted to a tuple without doing any sorting. I think that can mean that the order of the glyphs in that tuple can vary across implementations.

**Comment by anthrotype** [comment]
I tried to sort the tuple in 9e76d16, which seems to fix this issue, but now two other test cases fail: `test_FeatureFile_GPOS_2b` and `test_FeatureFile_spec6b_ii`:

https://travis-ci.org/fonttools/fonttools/jobs/187889444#L1216-L1281

I'm not sure how these are related.

**Comment by justvanrossum** [comment]
Hm, come to think of it, the order of glyphs in a fea group is often significant, so sorting it may be the wrong thing to do after all. Also: it appears that `ClassDefBuilder().add()` is often called with a tuple (at least from the now failing tests). So: either `ClassDefBuilder().add()` should not be called with a set, or the `glyphs` arg should only be sorted when it's a set. The latter doesn't sound very nice.

**Comment by anthrotype** [comment]
you're right, fea groups are not sets and have an order.
I shall revert the last commit, and adjust the otlLib.builder_test so that ClassDefBuilder add/canAdd are passed tuples instead of sets.

**Comment by anthrotype** [comment]
`otlLib.ClassDefBuilder` only receives sets in its own unit tests (`otlLib.builder_test`), whereas it gets tuples when used from feaLib.
I wouldn't like to modify the tests (by replacing sets with tuples) just to make them green..

I wonder whether I should do this instead: ie. allow both (unordered) sets and ordered sequences as input to ClassDefBuilder:

```diff
diff --git a/Lib/fontTools/otlLib/builder.py b/Lib/fontTools/otlLib/builder.py
index c7b753b..891c987 100644
--- a/Lib/fontTools/otlLib/builder.py
+++ b/Lib/fontTools/otlLib/builder.py
@@ -589,7 +589,10 @@ class ClassDefBuilder(object):
         self.useClass0_ = useClass0
 
     def canAdd(self, glyphs):
-        glyphs = tuple(glyphs)
+        if isinstance(glyphs, (set, frozenset)):
+            glyphs = tuple(sorted(glyphs))
+        elif not isinstance(glyphs, tuple):
+            glyphs = tuple(glyphs)
         if glyphs in self.classes_:
             return True
         for glyph in glyphs:
@@ -598,7 +601,10 @@ class ClassDefBuilder(object):
         return True
 
     def add(self, glyphs):
-        glyphs = tuple(glyphs)
+        if isinstance(glyphs, (set, frozenset)):
+            glyphs = tuple(sorted(glyphs))
+        elif not isinstance(glyphs, tuple):
+            glyphs = tuple(glyphs)
         if glyphs in self.classes_:
             return
         self.classes_.add(glyphs)
```
